### ISSUE TITLE
Small issue 

### ISSUE THREAD

**Issue by Cpandrej** [satoru8/BetterLightTheme#3]
The issue is that it's hard to read yellowish or orangish colored texts.
E.g 
![image](https://user-images.githubusercontent.com/46089397/60988308-a0f41d80-a343-11e9-9229-abb59496c0de.png)
![image](https://user-images.githubusercontent.com/46089397/60988446-ec0e3080-a343-11e9-853e-49a36acfe3a6.png)
There are also some difficulties reading green colored texts like this 
![image](https://user-images.githubusercontent.com/46089397/60988495-02b48780-a344-11e9-8f51-b90790b5c9cf.png)
There is no problem to read the names while hovering over them, but it's a bit annoying that it's needed to hover over them.

These aren't serious issues, but it would be nice if they got changed,

**Comment by satoru8** [comment]
New small update just pushed v1.5.3. Fixes some issues and removes that text shadow.

**Comment by Cpandrej** [comment]
Okay but it seems that the colored texts still need a small work.

**Comment by satoru8** [comment]
That's based per server on what colours each person picks. I can't control the millions of combinations of colours possible. You can change the background in the theme settings to something else that contrasts better overall. 

Support Server: http://discord.gg/fjvwb95

**Comment by Cpandrej** [comment]
Aight 
Yeah i thought of changing the theme a bit
